apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: geocentric-model-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: apps-of-apps

  source:
    repoURL: https://github.com/kasunsjc/argo-demo-apps.git
    targetRevision: HEAD
    path: ./declarative/mono-app/geocentric-model

  destination:
    server: https://kubernetes.default.svc
    namespace: declative-mono-app

  syncPolicy:
    syncOptions:
      - CreateNamespace=true  
    automated:
      prune: true
      selfHeal: true
